services:
  mysql:
    image: mysql:8.4.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: student_hub
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    image: backend
    build:
      context: backend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_NAME: student_hub
    depends_on:
      - mysql
  
  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: ./Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - backend

volumes:
  mysql-data: